### ISSUE TITLE
Value Errors

### ISSUE THREAD

**Issue by mpe721** [ctcampbell/veracode-to-csv#11]
Getting value errors with the data.py script 

![inkedvc2csv_2_li](https://user-images.githubusercontent.com/41084675/42533319-73a0fc9c-8457-11e8-96ac-f7378d19fa6f.jpg)
![vc2csv_1](https://user-images.githubusercontent.com/41084675/42533330-7a4b045c-8457-11e8-8901-d96f60cf5f51.PNG)

**Comment by ctcampbell** [comment]
Fixed in 2018.7.1
