### ISSUE TITLE
File does not exist

### ISSUE THREAD

**Issue by diegoromano** [ctcampbell/veracode-to-csv#12]
@ctcampbell can you help me pls? during the installation of "veracode_api_signing-17.0.0-py2.py3-none-any.whl" has displayed this error:

[root@srv ~]# pip install veracode_api_signing-17.0.0-py2.py3-none-any.whl
Requirement 'veracode_api_signing-17.0.0-py2.py3-none-any.whl' looks like a filename, but the file does not exist
Processing ./veracode_api_signing-17.0.0-py2.py3-none-any.whl
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/root/veracode_api_signing-17.0.0-py2.py3-none-any.whl'

tks for your help!!
snk

**Comment by mpe721** [comment]
@diegoromano , Look in the README.md because you will have to ask your contact source for the correct .whl file to be sent to you. That file you tried is for demo purposes. I am not affiliated with veracode, just another user.

**Comment by ctcampbell** [comment]
I've removed this dependency now. You can also install directly from PyPi as per the readme.
