### ISSUE TITLE
Results for all Builds Downloaded Every Run

### ISSUE THREAD

**Issue by paul-gould** [ctcampbell/veracode-to-csv#13]
Script reads the policy_updated_date from the buildlist XML at the start of each run and compares with the timestamp recorded in processed_builds.txt. However, when writing processed_builds.txt, the script uses the published_date from the buildinfo XML. In our case, policy_updated_date appears to be a couple of minutes later than published_date, so the script always flags every build for download.

I'm assuming this change from policy_updated_date to published_date is needed for some other functionality as it's done explicitly in data.py:

```python
for build in app.builds:
    analysis_unit_attrib = self._get_build_info(app.id, build.id).find("analysis_unit").attrib
    if "published_date" in analysis_unit_attrib:
        published_date_string = analysis_unit_attrib["published_date"][:22] + analysis_unit_attrib["published_date"][23:]
        build.published_date = parser.parse(published_date_string).astimezone(pytz.utc)
        build.policy_updated_date = build.published_date
```

**Comment by ctcampbell** [comment]
Thanks for the report Paul, I've replicated the issue locally, looking in to it now.
