### ISSUE TITLE
"Fixed" event is not always created for flaws that are no longer present in Veracode scans.

### ISSUE THREAD

**Issue by Azino10** [ctcampbell/veracode-to-csv#14]
The expectation is that events related to Veracode flaws will have statuses that include (but are not limited to) the following: New, Open, Re-Open and Fixed. Events with a status of "Fixed" should simply be the events in which the flaws no longer exist in a subsequent scan. However, there are cases in which new Veracode scans show that the flaw has been removed (likely due to being fixed) but there is no corresponding event created in Splunk with a "Fixed" status thus causing that flaw to still be flagged as "Open" within the confines of Splunk.

**Comment by ctcampbell** [comment]
Can you please provide a link to an application profile that exhibits this issue?

**Comment by Azino10** [comment]
https://analysiscenter.veracode.com/auth/index.jsp#ViewReportsResultSummary:44700:299899:3277185:3263108:3278861:

[app_name-Business_Services_RPSS_07102016_flaw_id-5.docx](https://github.com/ctcampbell/veracode-to-csv/files/2958091/app_name-Business_Services_RPSS_07102016_flaw_id-5.docx)

**Comment by Azino10** [comment]
Hello Chris,

I have attached a Word document that shows one of the flaws having that same issue of not having a "Fixed" event. However, the events that once showed up for this particular flaw are no longer present in Splunk. Please see document for details.

Please let me know what I can do to assist with your investigation.

[Splunk vs Veracode discrepancy.docx](https://github.com/ctcampbell/veracode-to-csv/files/2988574/Splunk.vs.Veracode.discrepancy.docx)

**Comment by Azino10** [comment]
Good morning Chris. I am checking in to see if there is any update on this. Please let me know if there is anything I can do to assist.

**Comment by dnyse1** [comment]
Hey Chris I have submitted a FEED ticket to possibly have more support for Splunk integrations, however, if you can look into this a bit more it would be greatly appreciated as Aflac relies on this correlation.

**Comment by ctcampbell** [comment]
I believe that this issue is resolved in the latest version. I have tested with Business_Services_RPSS_07102016 and flaw ID 5 is showing as fixed in scan RPSS_09142017. In total I see 7 events created for this flaw ID.

**Comment by Azino10** [comment]
I believe the issue is not reproducible at the moment so we can go ahead and close it. Thanks for your efforts Chris.

**Comment by ctcampbell** [comment]
Good to hear. Closing.
