### ISSUE TITLE
Flaw reopened in Splunk despite not being reopened in Veracode

### ISSUE THREAD

**Issue by Azino10** [ctcampbell/veracode-to-csv#16]
Good morning Chris,

I stumbled upon an issue in Splunk a few weeks ago in which a particular flaw had a 'New' event, a bunch of 'Open' events, a 'Fixed' event and, eventually, a 'Re-Open' event. I ran a query that allows me to see the specific build where that flaw was supposedly re-opened. When I go to that specific build, I do not see that flaw in there that was supposed to be re-opened (nor do I see any other flaws matching that flaw category). Is there a way to see what was in the Veracode export that was ingested by Splunk on the date where it saw that 'Re-Open' event?

This was the query in question:

index=veracode app_name="BusinessServices_MainWebAppACSS-CI-TFSPipeline" flaw_id=47
| convert ctime(_indextime) AS indexTime
|table _time indexTime flaw_remediation_status app_name flaw_module build_name build_policy_updated_date build_published_date flaw_date_first_occurrence flaw_affects_policy_compliance
|sort -_time

Thanks,

Azino Odhomi

**Comment by ctcampbell** [comment]
Thanks for the issue file Azino. Do you still have the csv files that were created when the script ran? You should have a file that contains the build id in the file name and in there should be the flaw showing as re-open. You can email me the file to check at ccampbell@veracode.com if so.

**Comment by ctcampbell** [comment]
I've pulled all scans for that app into my copy of Splunk and I don't see a re-open event. There are 17 entries for flaw ID 47, 1 new, 15 open and 1 fixed. The date of the fixed event is 23/07/19.

**Comment by Azino10** [comment]
Hi Chris,

I have attached a screenshot from Splunk showing where it was re-opened. It also shows that there was a different module where it was re-opened. Unfortunately, we no longer have the csv files that were created when the script ran.

<img width="957" alt="Flaw_47" src="https://user-images.githubusercontent.com/48482647/68695379-e9695500-0548-11ea-9ba0-987176cf0874.png">

**Comment by ctcampbell** [comment]
Could you run:

```
index="aflac" app_name="BusinessServices_MainWebAppACSS-CI-TFSPipeline" flaw_id=47
| convert ctime(_indextime) AS indexTime
| table _time indexTime flaw_id flaw_remediation_status app_name app_id flaw_module build_name build_id
| sort -_time
```

**Comment by Azino10** [comment]
We don't have an index="aflac" so I changed it to "Veracode".
<img width="952" alt="Flaw_47" src="https://user-images.githubusercontent.com/48482647/68701460-ccd31a00-0554-11ea-9524-e421ad60dc25.png">

**Comment by ctcampbell** [comment]
The build `20190724.1` has two scans against it, the activity log shows that you changed module selection and ran a rescan on the 31st July, which would impact the flaws identified. The timeline is

1. 24th July 5:38 EDT - Scan results published - flaw ID 47 reopened
2. 25th July 02:05 (Not sure what timezone your Splunk server is in) - Scan CSV indexed by Splunk, pulling in flaw ID 47 as 're-open'
3. 31st July 11:07 EDT - Scan module selection changed and resubmitted
4. 31st July 11:07 EDT - Updated scan results published - flaw ID 47 no longer present

I also noticed that this application is a .NET web application and you have not submitted pre-compiled views, I suggest having your developers configure TFS to perform this before uploading for a scan and this impacts the accuracy of the scan results. Our help center covers this at https://help.veracode.com/reader/4EKhlLSMHm5jC8P8j3XccQ/lCoP2W7Nvbc6tzlnFkg4gQ.

**Comment by Azino10** [comment]
I’m not sure I quite follow. Even if the rescan somehow caused this issue, that doesn’t explain why the re-opened flaw isn’t present in the Veracode Platform or on your end when you run your own search.

**Comment by ctcampbell** [comment]
The reopened flaw doesn’t show because it wasn’t found in the second scan after you changed the module selection. When you run a rescan the results from the first scan are completely overwritten.


________________________________

**Comment by Azino10** [comment]
Okay. I think we'll just have to programatically remove that flaw. Thanks for looking into it.
